# Generated by Django 6.0.3 on 2026-05-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='type',
            field=models.CharField(max_length=59),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
