# Generated by Django 6.0.3 on 2026-05-04 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_alter_inquiry_type_delete_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inquiries.type'),
        ),
    ]
