# Generated by Django 6.0.3 on 2026-05-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.IntegerField()),
                ('trim', models.CharField(blank=True, max_length=100)),
                ('drive', models.CharField(blank=True, choices=[('fwd', 'Front Wheel Drive'), ('rwd', 'Rear Wheel Drive'), ('awd', 'All Wheel Drive'), ('4wd', '4 Wheel Drive')], max_length=5)),
                ('body', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('van', 'Van'), ('convertible', 'Convertible')], max_length=15)),
                ('color', models.CharField(max_length=50)),
                ('engine_size', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True)),
                ('cylinders', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('coutner', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='car_images/%Y/%m/%d')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.brand')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.fuel')),
                ('gearbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.gearbox')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.model')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cars.car')),
            ],
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_available'], name='cars_car_is_avai_697038_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand', 'model'], name='cars_car_brand_i_c5fc6a_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price'], name='cars_car_price_f6b08b_idx'),
        ),
    ]
